apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-goerli
  namespace: wenmerge

spec:
  selector:
    matchLabels:
      app: redis-goerli
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: redis-goerli
    spec:
      containers:
      - name: redis
        image: redis:7.0.4-alpine3.16
        ports:
        - containerPort: 6379
