apiVersion: v1
kind: Service
metadata:
  name: svc-redis-goerli
  namespace: wenmerge

spec:
  type: ClusterIP
  selector:
    app: redis-goerli
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
