apiVersion: apps/v1
kind: Deployment
metadata:
  name: wenmerge-goerli-backend
  namespace: wenmerge

spec:
  selector:
    matchLabels:
      app: wenmerge-goerli-backend
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: wenmerge-goerli-backend
    spec:
      containers:
      - name: backend
        image: rootwarp/wenmerge-backend:latest
        ports:
        - containerPort: 9090
        env:
        - name: ETH_RPC_URL
          valueFrom:
            secretKeyRef:
              name: rpc-goerli-endpoints
              key: ETH_GOERLI_RPC_URL
        - name: ETH_WSS_URL
          valueFrom:
            secretKeyRef:
              name: rpc-goerli-endpoints
              key: ETH_GOERLI_WSS_URL

